title: yychiFYUkynn
author: yychi
email: guyueshui002@gmail.com
timezone: Asia/Shanghai
description: > # this means to ignore newlines until "baseurl:"
  To solutions, to knowledges.

# social links
#twitter_username: @fyuyychi
#github_username:  @guyueshui

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
